name: Scala CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Run tests
      run: sbt test
      
    - name: Indigo build
      run: sbt buildGame
        
    - name: Release to Github Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: ${{ secrets.TOKEN }}
          title: Release - Latest Version
          files: | 
            target/indigoBuild/*
            report/index.pdf
