name: Scala CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Run tests
      run: sbt test
      
    - name: Indigo build
      run: sbt buildGame
      
    - name: Zip site folder
      uses: "montudor/action-zip@v1"
      with:
       args: zip -qq -r target.zip target/indigoBuild
    
    - name: Automatic Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            target.zip
            report/index.pdf
